# 北京市主要道路基础数据（交通检测器部署点）
# 涵盖 10 个行政区，共 105 个检测器（21 个真实路口 × 5 个方向）

ROAD_DATA = [
    # === 海淀区 ===
    {"detector_id": "D00001", "detector_name": "中关村大街-海淀黄庄路口", "district": "海淀区",
     "lane_count": 4, "longitude": 116.312, "latitude": 39.989, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00002", "detector_name": "中关村大街-海淀黄庄路口", "district": "海淀区",
     "lane_count": 4, "longitude": 116.312, "latitude": 39.989, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00003", "detector_name": "中关村大街-海淀黄庄路口", "district": "海淀区",
     "lane_count": 4, "longitude": 116.312, "latitude": 39.989, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00004", "detector_name": "中关村大街-海淀黄庄路口", "district": "海淀区",
     "lane_count": 4, "longitude": 116.312, "latitude": 39.989, "road_type": "主干路", "direction": "西向东"},
    {"detector_id": "D00005", "detector_name": "学院路-五道口路口", "district": "海淀区",
     "lane_count": 4, "longitude": 116.324, "latitude": 39.998, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00006", "detector_name": "学院路-五道口路口", "district": "海淀区",
     "lane_count": 4, "longitude": 116.324, "latitude": 39.998, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00007", "detector_name": "学院路-清华东路口", "district": "海淀区",
     "lane_count": 3, "longitude": 116.328, "latitude": 40.003, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00008", "detector_name": "学院路-清华东路口", "district": "海淀区",
     "lane_count": 3, "longitude": 116.328, "latitude": 40.003, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00009", "detector_name": "西二旗大街-上地七街路口", "district": "海淀区",
     "lane_count": 4, "longitude": 116.306, "latitude": 40.051, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00010", "detector_name": "西二旗大街-上地七街路口", "district": "海淀区",
     "lane_count": 4, "longitude": 116.306, "latitude": 40.051, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00011", "detector_name": "知春路-中关村大街口", "district": "海淀区",
     "lane_count": 3, "longitude": 116.316, "latitude": 39.984, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00012", "detector_name": "知春路-中关村大街口", "district": "海淀区",
     "lane_count": 3, "longitude": 116.316, "latitude": 39.984, "road_type": "主干路", "direction": "西向东"},
    {"detector_id": "D00013", "detector_name": "上地信息路-上地三街", "district": "海淀区",
     "lane_count": 4, "longitude": 116.289, "latitude": 40.039, "road_type": "次干路", "direction": "南向北"},
    {"detector_id": "D00014", "detector_name": "上地信息路-上地三街", "district": "海淀区",
     "lane_count": 4, "longitude": 116.289, "latitude": 40.039, "road_type": "次干路", "direction": "北向南"},
    {"detector_id": "D00015", "detector_name": "学院南路-交大东路路口", "district": "海淀区",
     "lane_count": 3, "longitude": 116.336, "latitude": 39.945, "road_type": "次干路", "direction": "南向北"},

    # === 朝阳区 ===
    {"detector_id": "D00016", "detector_name": "望京SOHO周边道路", "district": "朝阳区",
     "lane_count": 4, "longitude": 116.472, "latitude": 39.996, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00017", "detector_name": "望京SOHO周边道路", "district": "朝阳区",
     "lane_count": 4, "longitude": 116.472, "latitude": 39.996, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00018", "detector_name": "望京SOHO周边道路", "district": "朝阳区",
     "lane_count": 4, "longitude": 116.472, "latitude": 39.996, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00019", "detector_name": "望京SOHO周边道路", "district": "朝阳区",
     "lane_count": 4, "longitude": 116.472, "latitude": 39.996, "road_type": "主干路", "direction": "西向东"},
    {"detector_id": "D00020", "detector_name": "国贸桥-建外大街", "district": "朝阳区",
     "lane_count": 5, "longitude": 116.446, "latitude": 39.908, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00021", "detector_name": "国贸桥-建外大街", "district": "朝阳区",
     "lane_count": 5, "longitude": 116.446, "latitude": 39.908, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00022", "detector_name": "国贸桥-建外大街", "district": "朝阳区",
     "lane_count": 5, "longitude": 116.446, "latitude": 39.908, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00023", "detector_name": "三里屯路-工体北路路口", "district": "朝阳区",
     "lane_count": 3, "longitude": 116.449, "latitude": 39.935, "road_type": "次干路", "direction": "南向北"},
    {"detector_id": "D00024", "detector_name": "三里屯路-工体北路路口", "district": "朝阳区",
     "lane_count": 3, "longitude": 116.449, "latitude": 39.935, "road_type": "次干路", "direction": "北向南"},
    {"detector_id": "D00025", "detector_name": "慈云寺路-东四环路口", "district": "朝阳区",
     "lane_count": 4, "longitude": 116.484, "latitude": 39.926, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00026", "detector_name": "慈云寺路-东四环路口", "district": "朝阳区",
     "lane_count": 4, "longitude": 116.484, "latitude": 39.926, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00027", "detector_name": "东四环中路-红庙路口", "district": "朝阳区",
     "lane_count": 4, "longitude": 116.458, "latitude": 39.921, "road_type": "快速路", "direction": "南向北"},
    {"detector_id": "D00028", "detector_name": "东四环中路-红庙路口", "district": "朝阳区",
     "lane_count": 4, "longitude": 116.458, "latitude": 39.921, "road_type": "快速路", "direction": "北向南"},

    # === 西城区 ===
    {"detector_id": "D00029", "detector_name": "西单北大街-西长安街路口", "district": "西城区",
     "lane_count": 4, "longitude": 116.373, "latitude": 39.914, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00030", "detector_name": "西单北大街-西长安街路口", "district": "西城区",
     "lane_count": 4, "longitude": 116.373, "latitude": 39.914, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00031", "detector_name": "西单北大街-西长安街路口", "district": "西城区",
     "lane_count": 4, "longitude": 116.373, "latitude": 39.914, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00032", "detector_name": "西单北大街-西长安街路口", "district": "西城区",
     "lane_count": 4, "longitude": 116.373, "latitude": 39.914, "road_type": "主干路", "direction": "西向东"},
    {"detector_id": "D00033", "detector_name": "复兴路-木樨地路口", "district": "西城区",
     "lane_count": 4, "longitude": 116.335, "latitude": 39.907, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00034", "detector_name": "复兴路-木樨地路口", "district": "西城区",
     "lane_count": 4, "longitude": 116.335, "latitude": 39.907, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00035", "detector_name": "阜成路-花园桥路口", "district": "西城区",
     "lane_count": 3, "longitude": 116.341, "latitude": 39.931, "road_type": "主干路", "direction": "东向西"},

    # === 东城区 ===
    {"detector_id": "D00036", "detector_name": "东单北大街-东长安街路口", "district": "东城区",
     "lane_count": 4, "longitude": 116.417, "latitude": 39.913, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00037", "detector_name": "东单北大街-东长安街路口", "district": "东城区",
     "lane_count": 4, "longitude": 116.417, "latitude": 39.913, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00038", "detector_name": "东单北大街-东长安街路口", "district": "东城区",
     "lane_count": 4, "longitude": 116.417, "latitude": 39.913, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00039", "detector_name": "东单北大街-东长安街路口", "district": "东城区",
     "lane_count": 4, "longitude": 116.417, "latitude": 39.913, "road_type": "主干路", "direction": "西向东"},
    {"detector_id": "D00040", "detector_name": "崇文门内大街-东单北大街", "district": "东城区",
     "lane_count": 3, "longitude": 116.414, "latitude": 39.905, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00041", "detector_name": "崇文门内大街-东单北大街", "district": "东城区",
     "lane_count": 3, "longitude": 116.414, "latitude": 39.905, "road_type": "主干路", "direction": "北向南"},

    # === 丰台区 ===
    {"detector_id": "D00042", "detector_name": "西三环南路-六里桥", "district": "丰台区",
     "lane_count": 5, "longitude": 116.311, "latitude": 39.884, "road_type": "快速路", "direction": "南向北"},
    {"detector_id": "D00043", "detector_name": "西三环南路-六里桥", "district": "丰台区",
     "lane_count": 5, "longitude": 116.311, "latitude": 39.884, "road_type": "快速路", "direction": "北向南"},
    {"detector_id": "D00044", "detector_name": "南三环西路-玉泉营桥", "district": "丰台区",
     "lane_count": 4, "longitude": 116.345, "latitude": 39.865, "road_type": "快速路", "direction": "南向北"},
    {"detector_id": "D00045", "detector_name": "南三环西路-玉泉营桥", "district": "丰台区",
     "lane_count": 4, "longitude": 116.345, "latitude": 39.865, "road_type": "快速路", "direction": "北向南"},
    {"detector_id": "D00046", "detector_name": "蒲黄榆路-刘家窑桥", "district": "丰台区",
     "lane_count": 3, "longitude": 116.423, "latitude": 39.868, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00047", "detector_name": "蒲黄榆路-刘家窑桥", "district": "丰台区",
     "lane_count": 3, "longitude": 116.423, "latitude": 39.868, "road_type": "主干路", "direction": "北向南"},

    # === 石景山区 ===
    {"detector_id": "D00048", "detector_name": "复兴路-公主坟路口", "district": "石景山区",
     "lane_count": 4, "longitude": 116.314, "latitude": 39.908, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00049", "detector_name": "复兴路-公主坟路口", "district": "石景山区",
     "lane_count": 4, "longitude": 116.314, "latitude": 39.908, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00050", "detector_name": "复兴路-公主坟路口", "district": "石景山区",
     "lane_count": 4, "longitude": 116.314, "latitude": 39.908, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00051", "detector_name": "石景山路-八角桥", "district": "石景山区",
     "lane_count": 4, "longitude": 116.225, "latitude": 39.907, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00052", "detector_name": "石景山路-八角桥", "district": "石景山区",
     "lane_count": 4, "longitude": 116.225, "latitude": 39.907, "road_type": "主干路", "direction": "西向东"},

    # === 通州区 ===
    {"detector_id": "D00053", "detector_name": "新华大街-通州北苑路口", "district": "通州区",
     "lane_count": 4, "longitude": 116.656, "latitude": 39.907, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00054", "detector_name": "新华大街-通州北苑路口", "district": "通州区",
     "lane_count": 4, "longitude": 116.656, "latitude": 39.907, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00055", "detector_name": "新华大街-通州北苑路口", "district": "通州区",
     "lane_count": 4, "longitude": 116.656, "latitude": 39.907, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00056", "detector_name": "运河西大街-物资学院路口", "district": "通州区",
     "lane_count": 3, "longitude": 116.634, "latitude": 39.918, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00057", "detector_name": "运河西大街-物资学院路口", "district": "通州区",
     "lane_count": 3, "longitude": 116.634, "latitude": 39.918, "road_type": "主干路", "direction": "西向东"},

    # === 昌平区 ===
    {"detector_id": "D00058", "detector_name": "北清路-永丰路路口", "district": "昌平区",
     "lane_count": 4, "longitude": 116.228, "latitude": 40.068, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00059", "detector_name": "北清路-永丰路路口", "district": "昌平区",
     "lane_count": 4, "longitude": 116.228, "latitude": 40.068, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00060", "detector_name": "北清路-永丰路路口", "district": "昌平区",
     "lane_count": 4, "longitude": 116.228, "latitude": 40.068, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00061", "detector_name": "永丰路-北清路路口", "district": "昌平区",
     "lane_count": 4, "longitude": 116.232, "latitude": 40.073, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00062", "detector_name": "永丰路-北清路路口", "district": "昌平区",
     "lane_count": 4, "longitude": 116.232, "latitude": 40.073, "road_type": "主干路", "direction": "北向南"},

    # === 大兴区 ===
    {"detector_id": "D00063", "detector_name": "京开高速-西红门南桥", "district": "大兴区",
     "lane_count": 5, "longitude": 116.342, "latitude": 39.798, "road_type": "高速", "direction": "南向北"},
    {"detector_id": "D00064", "detector_name": "京开高速-西红门南桥", "district": "大兴区",
     "lane_count": 5, "longitude": 116.342, "latitude": 39.798, "road_type": "高速", "direction": "北向南"},
    {"detector_id": "D00065", "detector_name": "南六环-京开高速入口", "district": "大兴区",
     "lane_count": 3, "longitude": 116.348, "latitude": 39.768, "road_type": "高速", "direction": "东向西"},
    {"detector_id": "D00066", "detector_name": "南六环-京开高速入口", "district": "大兴区",
     "lane_count": 3, "longitude": 116.348, "latitude": 39.768, "road_type": "高速", "direction": "西向东"},

    # === 顺义区 ===
    {"detector_id": "D00067", "detector_name": "顺平路-枯柳树环岛", "district": "顺义区",
     "lane_count": 3, "longitude": 116.653, "latitude": 40.128, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00068", "detector_name": "顺平路-枯柳树环岛", "district": "顺义区",
     "lane_count": 3, "longitude": 116.653, "latitude": 40.128, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00069", "detector_name": "顺义区-首都机场高速", "district": "顺义区",
     "lane_count": 4, "longitude": 116.608, "latitude": 40.053, "road_type": "高速", "direction": "南向北"},
    {"detector_id": "D00070", "detector_name": "顺义区-首都机场高速", "district": "顺义区",
     "lane_count": 4, "longitude": 116.608, "latitude": 40.053, "road_type": "高速", "direction": "北向南"},

    # === 高速公路 ===
    {"detector_id": "D00071", "detector_name": "京藏高速-西三旗入口", "district": "昌平区",
     "lane_count": 3, "longitude": 116.339, "latitude": 40.023, "road_type": "高速", "direction": "东向西"},
    {"detector_id": "D00072", "detector_name": "京藏高速-西三旗入口", "district": "昌平区",
     "lane_count": 3, "longitude": 116.339, "latitude": 40.023, "road_type": "高速", "direction": "西向东"},
    {"detector_id": "D00073", "detector_name": "京承高速-望和桥入口", "district": "朝阳区",
     "lane_count": 3, "longitude": 116.435, "latitude": 39.978, "road_type": "高速", "direction": "南向北"},
    {"detector_id": "D00074", "detector_name": "京承高速-望和桥入口", "district": "朝阳区",
     "lane_count": 3, "longitude": 116.435, "latitude": 39.978, "road_type": "高速", "direction": "北向南"},
    {"detector_id": "D00075", "detector_name": "京沪高速-分钟寺桥入口", "district": "朝阳区",
     "lane_count": 4, "longitude": 116.475, "latitude": 39.873, "road_type": "高速", "direction": "南向北"},
    {"detector_id": "D00076", "detector_name": "京沪高速-分钟寺桥入口", "district": "朝阳区",
     "lane_count": 4, "longitude": 116.475, "latitude": 39.873, "road_type": "高速", "direction": "北向南"},

    # === 支路补充 ===
    {"detector_id": "D00077", "detector_name": "五道口地铁站周边道路", "district": "海淀区",
     "lane_count": 2, "longitude": 116.319, "latitude": 39.997, "road_type": "支路", "direction": "南向北"},
    {"detector_id": "D00078", "detector_name": "五道口地铁站周边道路", "district": "海淀区",
     "lane_count": 2, "longitude": 116.319, "latitude": 39.997, "road_type": "支路", "direction": "北向南"},
    {"detector_id": "D00079", "detector_name": "西二旗地铁站周边道路", "district": "海淀区",
     "lane_count": 2, "longitude": 116.308, "latitude": 40.049, "road_type": "支路", "direction": "东向西"},
    {"detector_id": "D00080", "detector_name": "西二旗地铁站周边道路", "district": "海淀区",
     "lane_count": 2, "longitude": 116.308, "latitude": 40.049, "road_type": "支路", "direction": "西向东"},
    {"detector_id": "D00081", "detector_name": "北京站站前街", "district": "东城区",
     "lane_count": 3, "longitude": 116.427, "latitude": 39.904, "road_type": "支路", "direction": "南向北"},
    {"detector_id": "D00082", "detector_name": "北京站站前街", "district": "东城区",
     "lane_count": 3, "longitude": 116.427, "latitude": 39.904, "road_type": "支路", "direction": "北向南"},
    {"detector_id": "D00083", "detector_name": "朝阳门内大街-朝阳门桥", "district": "东城区",
     "lane_count": 4, "longitude": 116.434, "latitude": 39.928, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00084", "detector_name": "朝阳门内大街-朝阳门桥", "district": "东城区",
     "lane_count": 4, "longitude": 116.434, "latitude": 39.928, "road_type": "主干路", "direction": "西向东"},
    {"detector_id": "D00085", "detector_name": "东六环-通州北关入口", "district": "通州区",
     "lane_count": 3, "longitude": 116.647, "latitude": 39.931, "road_type": "高速", "direction": "南向北"},
    {"detector_id": "D00086", "detector_name": "东六环-通州北关入口", "district": "通州区",
     "lane_count": 3, "longitude": 116.647, "latitude": 39.931, "road_type": "高速", "direction": "北向南"},
    {"detector_id": "D00087", "detector_name": "立汤路-天通苑路口", "district": "昌平区",
     "lane_count": 4, "longitude": 116.407, "latitude": 40.072, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00088", "detector_name": "立汤路-天通苑路口", "district": "昌平区",
     "lane_count": 4, "longitude": 116.407, "latitude": 40.072, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00089", "detector_name": "天通苑周边道路", "district": "昌平区",
     "lane_count": 2, "longitude": 116.412, "latitude": 40.067, "road_type": "支路", "direction": "南向北"},
    {"detector_id": "D00090", "detector_name": "天通苑周边道路", "district": "昌平区",
     "lane_count": 2, "longitude": 116.412, "latitude": 40.067, "road_type": "支路", "direction": "北向南"},
    {"detector_id": "D00091", "detector_name": "酒仙桥路-将台路口", "district": "朝阳区",
     "lane_count": 3, "longitude": 116.487, "latitude": 39.959, "road_type": "次干路", "direction": "南向北"},
    {"detector_id": "D00092", "detector_name": "酒仙桥路-将台路口", "district": "朝阳区",
     "lane_count": 3, "longitude": 116.487, "latitude": 39.959, "road_type": "次干路", "direction": "北向南"},
    {"detector_id": "D00093", "detector_name": "东三环南路-潘家园桥", "district": "朝阳区",
     "lane_count": 5, "longitude": 116.442, "latitude": 39.877, "road_type": "快速路", "direction": "南向北"},
    {"detector_id": "D00094", "detector_name": "东三环南路-潘家园桥", "district": "朝阳区",
     "lane_count": 5, "longitude": 116.442, "latitude": 39.877, "road_type": "快速路", "direction": "北向南"},
    {"detector_id": "D00095", "detector_name": "西二旗大街-西二旗桥", "district": "海淀区",
     "lane_count": 3, "longitude": 116.299, "latitude": 40.046, "road_type": "次干路", "direction": "东向西"},
    {"detector_id": "D00096", "detector_name": "西二旗大街-西二旗桥", "district": "海淀区",
     "lane_count": 3, "longitude": 116.299, "latitude": 40.046, "road_type": "次干路", "direction": "西向东"},
    {"detector_id": "D00097", "detector_name": "西四环南路-岳各庄桥", "district": "丰台区",
     "lane_count": 4, "longitude": 116.278, "latitude": 39.883, "road_type": "快速路", "direction": "南向北"},
    {"detector_id": "D00098", "detector_name": "西四环南路-岳各庄桥", "district": "丰台区",
     "lane_count": 4, "longitude": 116.278, "latitude": 39.883, "road_type": "快速路", "direction": "北向南"},
    {"detector_id": "D00099", "detector_name": "丰台科技园周边道路", "district": "丰台区",
     "lane_count": 3, "longitude": 116.282, "latitude": 39.831, "road_type": "次干路", "direction": "南向北"},
    {"detector_id": "D00100", "detector_name": "丰台科技园周边道路", "district": "丰台区",
     "lane_count": 3, "longitude": 116.282, "latitude": 39.831, "road_type": "次干路", "direction": "北向南"},
    {"detector_id": "D00101", "detector_name": "宋家庄地铁站周边道路", "district": "丰台区",
     "lane_count": 2, "longitude": 116.428, "latitude": 39.841, "road_type": "支路", "direction": "南向北"},
    {"detector_id": "D00102", "detector_name": "宋家庄地铁站周边道路", "district": "丰台区",
     "lane_count": 2, "longitude": 116.428, "latitude": 39.841, "road_type": "支路", "direction": "北向南"},
    {"detector_id": "D00103", "detector_name": "望京西路-望京桥", "district": "朝阳区",
     "lane_count": 4, "longitude": 116.459, "latitude": 39.973, "road_type": "主干路", "direction": "南向北"},
    {"detector_id": "D00104", "detector_name": "望京西路-望京桥", "district": "朝阳区",
     "lane_count": 4, "longitude": 116.459, "latitude": 39.973, "road_type": "主干路", "direction": "北向南"},
    {"detector_id": "D00105", "detector_name": "回龙观西大街-回龙观桥", "district": "昌平区",
     "lane_count": 3, "longitude": 116.326, "latitude": 40.074, "road_type": "主干路", "direction": "东向西"},
    {"detector_id": "D00106", "detector_name": "回龙观西大街-回龙观桥", "district": "昌平区",
     "lane_count": 3, "longitude": 116.326, "latitude": 40.074, "road_type": "主干路", "direction": "西向东"},
]
